# Site settings
author: Ashley J. Bland
title: Learning to Code
header-img: img/home-bg.png
email: ashleyjbland@gmail.com
copyright_name: Ashley J. Bland
description: > # this means to ignore newlines until "baseurl:"
  One day at a time.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ashleyjbland

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
